messages:
  responses:
    put_public_page: "üìù *–û—Ç–ø—Ä–∞–≤—å—Ç–µ —Ç–µ–∫—Å—Ç –∑–∞—è–≤–∫–∏ –±–æ—Ç—É –≤ —Å–ª–µ–¥—É—é—â–µ–º —Ñ–æ—Ä–º–∞—Ç–µ:*\n\n1\\.\\ –ü—Ä–æ–¥–∞–∂–∞/–ü–æ–∫—É–ø–∫–∞ \\(–í—ã–±—Ä–∞—Ç—å –æ–¥–Ω–æ –∏–∑ –¥–≤—É—Ö\\)\n2\\.\\ –ü—Ä–æ—Ñ–∏–ª—å/–ö–∞–Ω–∞–ª \\(–í—ã–±—Ä–∞—Ç—å –æ–¥–Ω–æ –∏–∑ –¥–≤—É—Ö\\)\n3\\.\\ –°—Å—ã–ª–∫–∞ \n4\\.\\ –ö—Ä–∞—Ç–∫–æ–µ –æ–ø–∏—Å–∞–Ω–∏–µ –∏ –ø–æ–∂–µ–ª–∞–Ω–∏—è \n5\\.\\ –¶–µ–Ω–∞ –∏ —É—Å–ª–æ–≤–∏—è"
    after_submitting_public_page: "‚òëÔ∏è *–í–∞—à–∞ –∑–∞—è–≤–∫–∞ –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω–∞ –Ω–∞ –º–æ–¥–µ—Ä–∞—Ü–∏—é*"
    reject_public_page: "‚ùå *–ö —Å–æ–∂–∞–ª–µ–Ω–∏—é, –≤–∞—à–∞ –∑–∞—è–≤–∫–∞ –Ω–µ –ø—Ä–æ—à–ª–∞ –º–æ–¥–µ—Ä–∞—Ü–∏—é*\\.\\ –ü–æ–ø—Ä–æ–±—É–π—Ç–µ –≤–Ω–µ—Å—Ç–∏ –ø—Ä–∞–≤–∫–∏ –∏ –æ—Ç–ø—Ä–∞–≤–∏—Ç—å –∑–∞—è–≤–∫—É —Å–Ω–æ–≤–∞ \n\n–° —É–≤–∞–∂–µ–Ω–∏–µ–º,\n–ë–∏—Ä–∂–∞ —Ä–µ–∫–ª–∞–º—ã Ton\\.\\Place"
    after_payment_response: "üíé *–ë–ª–∞–≥–æ–¥–∏–º –≤–∞—Å –∑–∞ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏–µ —Å–µ—Ä–≤–∏—Å–∞*\\.\\ –í —Ç–µ—á–µ–Ω–∏–µ 2\\-\\5 –º–∏–Ω—É—Ç —Å—Ç–∞—Ç—É—Å –∑–∞—è–≤–∫–∏ –æ–±–Ω–æ–≤–∏—Ç—Å—è"
    failed_payment_response: "‚ùå *–ö —Å–æ–∂–∞–ª–µ–Ω–∏—é –æ–ø–ª–∞—Ç–∞ —Å –≤–∞—à–µ–π —Å—Ç–æ—Ä–æ–Ω—ã –Ω–µ –ø–æ—Å—Ç—É–ø–∏–ª–∞ –∏ –∑–∞—è–≤–∫–∞ –±—ã–ª–∞ —É–¥–∞–ª–µ–Ω–∞*\\.\\ –ü–æ–ø—Ä–æ–±—É–π—Ç–µ –æ—Ç–ø—Ä–∞–≤–∏—Ç—å –∑–∞—è–≤–∫—É —Å–Ω–æ–≤–∞\n\n–° —É–≤–∞–∂–µ–Ω–∏–µ–º,\n–ë–∏—Ä–∂–∞ —Ä–µ–∫–ª–∞–º—ã Ton\\.\\Place"
    success_payment_response: "‚òëÔ∏è *–í–∞—à–∞ –∑–∞—è–≤–∫–∞ –±—ã–ª–∞ –æ–¥–æ–±—Ä–µ–Ω–∞ –∏ –æ–ø—É–±–ª–∏–∫–æ–≤–∞–Ω–∞* \n\n–° —É–≤–∞–∂–µ–Ω–∏–µ–º,\n–ë–∏—Ä–∂–∞ —Ä–µ–∫–ª–∞–º—ã Ton\\.\\Place"
    payment_message: "–î–ª—è –ø—É–±–ª–∏–∫–∞—Ü–∏–∏ –∑–∞—è–≤–∫–∏ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ –¥–æ–±–∞–≤–∏—Ç—å –∫–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π –∫ –ø–ª–∞—Ç–µ–∂—É, –∫–æ—Ç–æ—Ä—ã–π —É–∫–∞–∑–∞–Ω –Ω–∏–∂–µ, –ø–µ—Ä–µ–≤–µ—Å—Ç–∏ %süíé, –∏ –ø–æ—Å–ª–µ —É—Å–ø–µ—à–Ω–æ–≥–æ –ø–µ—Ä–µ–≤–æ–¥–∞ –¥–µ–Ω–µ–≥ –Ω–∞–∂–∞—Ç—å –∫–Ω–æ–ø–∫—É %s\n\n*–ö–æ—à–µ–ª–µ–∫*:  `\\%s`\\ \n*–ö–æ–º–º–µ–Ω—Ç–∞—Ä–∏–π –∫ –ø–ª–∞—Ç–µ–∂—É*: `\\%s`\\ \n"
    already_paid: "‚ùå *–≠—Ç–∞ –∑–∞—è–≤–∫–∞ —É–∂–µ –±—ã–ª–∞ –æ–ø–ª–∞—á–µ–Ω–∞ –∏ –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω–∞*\\.\\ –ü–æ–¥–∞–π—Ç–µ –Ω–æ–≤—É—é –∑–∞—è–≤–∫—É, –ø–æ–∂–∞–ª—É–π—Å—Ç–∞"
    signature: "‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî‚Äî\nüìù –°–æ–∑–¥–∞—Ç—å –∑–∞—è–≤–∫—É: %s"
    contacts: "üë• *–°–æ–æ–±—â–µ—Å—Ç–≤–æ*:\n‚Ä¢ ton\\.\\place/group10316\n\n‚òéÔ∏è *–ö–æ–Ω—Ç–∞–∫—Ç—ã*:\n‚Ä¢ ton\\.\\place/id39469\n‚Ä¢ @goreactdev"

buttons:
  buy_ad: "üìù –ü—Ä–∞–π—Å-–ª–∏—Å—Ç (—Å—Å—ã–ª–∫–∞ –Ω–∞ —Ç–µ–ª–µ–≥—Ä–∞—Ñ)"
  contacts: "üìá –ö–æ–Ω—Ç–∞–∫—Ç—ã"
  back_to_previous: "‚Üê –ù–∞–∑–∞–¥"
  paid_button: "‚òëÔ∏è –û–ø–ª–∞—á–µ–Ω–æ"
  decline_paid_button: "‚ùå –û—Ç–∫–ª–æ–Ω–∏—Ç—å"
  choose_public_page_button: "üì£ –ö—É–ø–∏—Ç—å —Ä–µ–∫–ª–∞–º—É"
  create_request_button: "üìù –ü—É–±–ª–∏–∫–∞—Ü–∏—è –Ω–∞ –±–∏—Ä–∂–µ"
  approve_public_page_button: "‚òëÔ∏è –û–¥–æ–±—Ä–∏—Ç—å"
  decline_public_page_button: "‚ùå –û—Ç–∫–ª–æ–Ω–∏—Ç—å"
  rejected_button: "‚ùå –û—Ç–∫–ª–æ–Ω–µ–Ω–æ"
  approved_button: "‚òëÔ∏è –û–¥–æ–±—Ä–µ–Ω–æ"

public_pages:
  programmer_button: "üíª –ü—Ä–æ–≥—Ä–∞–º–º–∏—Å—Ç"
  aboutton_button: "üíé –í—Å—ë –æ TON"
